// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkng-xcsh8_q_TiJ6FMnRSCQBJoGejBc',
    appId: '1:708101899355:web:d381a9ed9c4214a60fab7e',
    messagingSenderId: '708101899355',
    projectId: 'prueba-19640',
    authDomain: 'prueba-19640.firebaseapp.com',
    storageBucket: 'prueba-19640.appspot.com',
    measurementId: 'G-S6HYXVT073',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ65GGZk127MeV5V7sEjbgYftVqoOLt7U',
    appId: '1:708101899355:android:33db0d2062eb175c0fab7e',
    messagingSenderId: '708101899355',
    projectId: 'prueba-19640',
    storageBucket: 'prueba-19640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI2rCcPS8WGCimFvgSxNTyPFsSt9nDS1g',
    appId: '1:708101899355:ios:11aff503325df2b40fab7e',
    messagingSenderId: '708101899355',
    projectId: 'prueba-19640',
    storageBucket: 'prueba-19640.appspot.com',
    iosBundleId: 'com.example.aplicacionTaxis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI2rCcPS8WGCimFvgSxNTyPFsSt9nDS1g',
    appId: '1:708101899355:ios:11aff503325df2b40fab7e',
    messagingSenderId: '708101899355',
    projectId: 'prueba-19640',
    storageBucket: 'prueba-19640.appspot.com',
    iosBundleId: 'com.example.aplicacionTaxis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClkng-xcsh8_q_TiJ6FMnRSCQBJoGejBc',
    appId: '1:708101899355:web:dc725fde326ee3310fab7e',
    messagingSenderId: '708101899355',
    projectId: 'prueba-19640',
    authDomain: 'prueba-19640.firebaseapp.com',
    storageBucket: 'prueba-19640.appspot.com',
    measurementId: 'G-6FP77E01BB',
  );
}
